spring:
  profiles:
    active: dev
  # 邮箱设置
  mail:
    port: 465
    host: smtp.qq.com
    username: 3014816817@qq.com
    password: yospgamvcmtpddbj
    properties:
      mail:
        auth: true
        transport:
          protocol: smtp
        debug: true
        smtp:
          ssl:
            enable: true
          starttls:
            enable: false
            required: false
