spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8080
    nacos:
      config:
        context-path: /view-api
  # activiti 工作流配置信息
  activiti:
    # flase：       默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。（生产环境常用）
    # true：        activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。（开发时常用）
    # create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。（单元测试常用）
    # drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。
    database-schema-update: true
    # 默认不生成历史表，这里开启
    db-history-used: true
    # 历史登记
    # none: 不记录历史流程，性能高，流程结束后不可读取
    # activity: 归档流程实例和活动实例，流程变量不同步
    # audit: 默认值，在activiti基础上同步变量值，保存表单属性
    # full: 性能较差，记录所有实例和变量细节变化，最完整的历史记录，如果需要日后跟踪详细可以开启full（一般不建议开启）
    history-level: full
    # 关闭 SpringAutoDeployment（每次重启都会生成一条工作流记录）
    deployment-mode: never-fail

  # 数据库 配置信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.228.32:3306/db-iw?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: likey
    password: likeyLi73+!
    # hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10 # 为了性能考虑，不建议设置此值，而是让HikariCP把连接池当做固定大小的处理，默认minimumIdle与maximumPoolSize一样
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000 # 当minimumIdle<maximumPoolSize时才生效，空闲连接数超过minimumIdle且空闲时间超过idleTimeout，则会被移除
      pool-name: ProductHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
springdoc:
  group-configs:
    basePath: /view-api